version: '3.9'
services:
  blog-app:
    build: .
    container_name: 'blog-app'
    image: va-admin
    environment:
      PG_URL: 'postgresql://user:blogs@postgres:5432/BLOG_DB?sslmode=disable'
    ports:
      - "8089:8089"
    networks:
      - user-network
    command: [ "/app/main" ]

networks:
  user-network:
    driver: bridge
